In [1]:
from annotator import Annotator
from personal_token import Label_Metrics
import graphs as gr
import pandas as pd
import warnings

warnings.filterwarnings("ignore", category=RuntimeWarning)
annotator1 = Annotator('annotator1', "annotations-TBikaun.json")
annotator2 = Annotator('annotator2', "annotations-ziyu.zhao.json")
annotator3 = Annotator('annotator3', "annotations-danielsantosa.json")
annotator4 = Annotator('annotator4', "annotations-mhodki.json")
annotator5 = Annotator('annotator5', "annotations-mstewartuwa.json")
annotator6 = Annotator('annotator6', "annotations-caitlinwoods.json")
annotator7 = Annotator('annotator7', "annotations-Tim.json")
label = Label_Metrics(annotator1, annotator2, annotator3)
overall_table = label.get_accumulated_table_labels()

In [2]:
agreements = label.get_annotator_token_agreements(overall_table)
annotator1_agreements = { 'annotator1': agreements['annotator1'] }
annotator1_summary = label.create_agreement_summary(annotator1_agreements)
annotator1_summary['annotator1']

,lowest agreement,medium-low agreement,medium agreement,medium-high agreement,high agreement
0,NaN,jack,"""",on,switch
1,NaN,pump drive,mast,wrench,NaN
2,NaN,pipe,raise.,in,NaN
3,NaN,valve,t,deck,NaN
4,NaN,button,won,oil,NaN
...,...,...,...,...,...
315,NaN,NaN,discharge,NaN,NaN
316,NaN,NaN,discharge gauges,NaN,NaN
317,NaN,NaN,gauges,NaN,NaN
318,NaN,NaN,pressure,NaN,NaN
319,NaN,NaN,faulty,NaN,NaN